server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    drop-first: false
  datasource:
    url: jdbc:mysql://localhost:3306/vr?useLegacyDatetimeCode=false&serverTimezone=America/New_York
    username: rl
    password: cimitery
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 128MB
      max-request-size: 128MB
  mail:
    host:
    port:
    username:
    password:
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 2272323049650627
    clientSecret:
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: 6fe891c133ea9427131a
    clientSecret: 97f73f8c8f5271c3ed174e46b8fd7fa3b0160435
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user


logging:
  level:
    org.springframework.security: DEBUG
app:
  security:
    basic:
      enabled: false
