server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    drop-first: true
    enabled: false
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 2272323049650627
    clientSecret:
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: 67dd380e2dd4c0a0d6ff
    clientSecret: 2383143b68a258d63bc6ffc4caa12abcdf0ce324
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user


logging:
  level:
    org.springframework.security: DEBUG