server:
  port: 8080
---
spring:
  profiles: prod, default
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    drop-first: true
    enabled: false
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

github:
  client:
    clientId: 67dd380e2dd4c0a0d6ff
    clientSecret:
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user


logging:
  level:
    org.springframework.security: DEBUG

