server:
  port: 8080
  contextPath: /vr

---
spring:
  profiles: prod, default
datasource:
  vr:
    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net
    username: b2bce111577fff
    password: 201c397b
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: heroku_e5f435f142d9681
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect