server:
  port: 8080
#  servlet:
#    context-path: /vr
#---
#spring:
#  profiles: local
#datasource:
#  vr:
#    url: jdbc:h2:~/test
#    username: SA
#    password:
#    driverClassName: org.h2.Driver
#    defaultSchema:
#    maxPoolSize: 10
#    hibernate:
#      hbm2ddl.method: create-drop
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod, default
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    drop-first: true
  datasource:
    url: jdbc:mysql://localhost:3306/vr?useLegacyDatetimeCode=false&serverTimezone=America/New_York
    username: rl
    password: cimitery
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 2272323049650627
    clientSecret: e67461a7c4e8562037e1c011b2461887
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: 67dd380e2dd4c0a0d6ff
    clientSecret: 2383143b68a258d63bc6ffc4caa12abcdf0ce324
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user


logging:
  level:
    org.springframework.security: DEBUG
#  security:
#    user:
#      name: user
#      password: password
#    oauth2:
#      client:
#        provider: github
#        clientId: 6fe891c133ea9427131a
#        clientSecret: 97f73f8c8f5271c3ed174e46b8fd7fa3b0160435
#        redirectUri: http://localhost:8080/vr/login/oauth2/code/github
#        clientName: Virtual Remembrance
#        scope: user

#    oauth2:
#      client:
#        provider: github
#        registration:
#          github:
#            scope: user
#            client-id: 6fe891c133ea9427131a
#            client-secret: 97f73f8c8f5271c3ed174e46b8fd7fa3b0160435
#            client-name: Virtual Remembrance
#            redirect-uri-template: http://localhost:8080/vr/login/oauth2/code/github

#datasource:
#  vr:
#    url: jdbc:mysql://localhost:3306/vr?useLegacyDatetimeCode=false&serverTimezone=America/New_York
#    username: rl
#    password: cimitery
#    driverClassName: com.mysql.cj.jdbc.Driver
#    defaultSchema:
#    maxPoolSize: 20
#    hibernate:
#      hbm2ddl.method: update
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQLDialect
#liquibase:
#  change-log: classpath:db/liquibase-changelog.xml
#  drop-first: true
